### ISSUE TITLE
DPVS performance evaluation

### ISSUE THREAD

**Issue by lapd-viosoft** [iqiyi/dpvs#54]
Hi,
I would like to replicate your performance test results on our servers.
Would you mind to share more detailed in your test setup? (such as test diagram,  how to setup the test, how to run the test ..)
Thank you!

**Comment by beacer** [comment]
We use HTTP clients (`wrk`) and servers (`nginx`) to test, `clients <-> dpvs <-> servers`.
All machines (clients/servers/dpvs) are physical machines,

* OS: CentOS 7.2.
* Kernel: 3.10.0-327.el7.x86_64
* CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
* NICs: Intel Corporation Ethernet Controller 10-Gigabit X540-AT2 (rev 03)

When test, we have 5 HTTP clients running `wrk` and another 5 for `Nginx`. The kernel sysctl parameter and **IRQ affinity** **must be** optimized on clients and servers.
* https://github.com/majek/ixgbe/blob/master/scripts/set_irq_affinity
* Make Nginx return short text instead of file.
```
        location / {
                default_type text/plain;
                return 200 "hello\n";
        }
```

For `DPVS` setting, pls refer: https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md .

**Comment by lapd-viosoft** [comment]
Thank Lei,
I'm able to set up the test. However, the client app wrk report Requests/sec and Transfer/sec, how did you translate them to packet per second?
And from your test report, with 07 cores, DPVS can reach to ~14Mpps with packet size = 64 bytes, it's line rate for 10G NIC! . 
Is it ok to say that we can get line rate (packet size = 64 bytes) with DPVS (using 7 cores)?
Thank you!

**Comment by beacer** [comment]
We calculate pps by `dpip link show` command. When we test, the avg packet size is 98B instead of 64B, because we are useing `wrk` to test HTTP request/response，and disable "keepalive" on Nginx. When using 7 cores we get the line-rate for 10G NIC (with 98B).

**Comment by lapd-viosoft** [comment]
Thank you for your explanation!

**Comment by tiepnv-viosoft** [comment]
Hi beacer,
Could you let me know which mode did you use to do Performance Test?

Thanks,

**Comment by beacer** [comment]
@tiepnv-viosoft FNAT mode.

**Comment by tiepnv-viosoft** [comment]
Thank you for your reply,
Is it the FNAT_1arm?

**Comment by beacer** [comment]
Both one-arm and two arm are tested, the data in README.md is two-arm.

**Comment by tiepnv-viosoft** [comment]
Thank you very much for your support!

**Comment by tiepnv-viosoft** [comment]
Hi beacer,
As you said that:

> We calculate pps by dpip link show command

Could you explain me specifically how to get pps parameter in dpvs?
I also ran `ipvsadm -ln --rate` and `dpip link -s show` but they didn't show any expected output.

I look forward to receiving your help soon.
Thanks,

**Comment by ywc689** [comment]
`ipvsadm -ln --rate` is not supported by dpvs yet.  You can try something like this `dpip link -s show dpdk0 i 3 -C` to get PPS of specified device.

**Comment by tiepnv-viosoft** [comment]
Thank you very much!
