### ISSUE TITLE
snat不能跑在kvm虚拟机上？

### ISSUE THREAD

**Issue by liangfudeng** [iqiyi/dpvs#80]
dpvs snat需要flowdirector，但是目前kvm virtio不支持flow director。不知道理解对不对，是否有代替方案。

**Comment by beacer** [comment]
Flow director (fdir) is necessary for multi-core configure with SNAT/FNAT mode of DPVS now, it's the fastest way we found.
For the NIC without fdir support, there are also some alternated options, such as RSS calculate for local port selection, and packet reschedule between cores, but for now, we have **no time** to develop them due to limited developer resource.
If any one want to contribute, we'll be very glad, and we can discuss the ideas for NIC without FDIR in detail.

**Comment by liangfudeng** [comment]
e1000 and virtio  without rss support too。single core is the only way?

**Comment by beacer** [comment]
DPVS is for high performance, if running load balancer on VM with 1G or less NIC or little number of CPU cores, I think LVS's performance is good enough.
To support SNAT/FNAT without fdir, the code will be much complicated, since packets need be re-scheduled among CPU cores.

**Comment by liangfudeng** [comment]
thanks for you response。 I have change some code for kvm .it is running now.

**Comment by beacer** [comment]
@liangfudeng sounds grate, can you pls show which codes for KVM you've changed ? so that other users can get benefited.
